version: '3.5'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 21
      MYSQL_DATABASE: database
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
    restart: always
    volumes:
      - mariadb:/var/lib/mysql:rw

  web:
    build: ./app
    ports:
      - 8080:80
    links:
      - db:db
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    links:
      - db:db

volumes:
  mariadb: